### ISSUE TITLE
본인 채팅은 오른쪽 정렬

### ISSUE THREAD

**Issue by acidsound** [Appsoulute/Firewox#2]
```css
.message.own {
  text-align: right;
  padding-right: 70px;
}
.message.own .thumb {
  right: 24px;
  left: auto;  
}
```
현재 설정에서 오른쪽 정렬로 해놓았는데 본인의 이름과 아바타 역할을 굳이 노출해야하나 싶음.

**Comment by acidsound** [comment]
![image](https://user-images.githubusercontent.com/623157/56217128-a66ffd80-609d-11e9-9528-5a2a9752055a.png)
위 css 적용 시 화면 캡쳐

**Comment by acidsound** [comment]
upstream 변경분 반영
```css
.message.own {
  text-align: right;
  padding-right: 70px;
}
.message.own .thumb {
  right: 24px;
  left: auto;  
}
.message.own .title {
  justify-content: flex-end;
}
```
